---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  sudo: yes

- name: Create webroot
  file:
    state: directory
    path: /srv/www
    owner: root
    group: root
    mode: 0755
  sudo: yes

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /srv/www/
    owner: www-data
    group: www-data
    copy: no
  sudo: yes

- name: Update default Nginx site
  replace: dest=/etc/nginx/sites-available/default regexp="(^.root /usr/share/nginx/html;)" replace="\troot /srv/www/wordpress;"
  notify:
    - restart nginx
  sudo: yes

- name: Move wp-config-sample.php
  command: mv /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php creates=/srv/www/wordpress/wp-config.php
  sudo: yes

- name: Update WordPress config file
  lineinfile:
    dest: /srv/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
  sudo: yes
