---
# tasks file for server

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install server software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - nginx
    - mysql-server
    - python-mysqldb
    - php5-fpm
    - php5
    - git
