---
# tasks file for php

- name: Install php extensions
  apt:
    name: "{{ item }}"
    state: present

  sudo: yes
  with_items:
    - php5-gd
    - libssh2-php
    - php5-mysql
    - php5-mcrypt

- name: Setup php-fpm
  replace: dest=/etc/php5/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
  notify:
    - restart nginx
  sudo: yes
